#!/usr/bin/env python

import sys

from omniveyor_gui.omniveyor_gui import GUI
from rqt_gui.main import Main

plugin = 'omniveyor_gui.omniveyor_gui.GUI'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin)) 
